### ISSUE TITLE
Bug: Page outside the site get into the wappalyzer report (in case of redirection)

### ISSUE THREAD

**Issue by jdauphant** [SocialGouv/wappalyzer-action#73]
In this result, we have infogram : https://raw.githubusercontent.com/betagouv/dashlord/a16832fd8b51a27846bf096f31ab32fbc6eccb54/results/aHR0cHM6Ly9tb24tc3VpdmktanVzdGljZS5iZXRhLmdvdXYuZnI%3D/wappalyzer.json

It's because /stats redirect to infogram.

**Comment by revolunet** [comment]
Indeed, thats weird, wappalyzer is not supposed to analyse externals urls.

Currently [the wappalyzer action](https://github.com/SocialGouv/wappalyzer-action/blob/master/src/scan.js#L7) use `depth: 3` when crawling the website, we could disable that as an immediate fix and only analyse the main URL.

Meanwhile, someone should try to seek & destroy the bug in [wappalyzer source](https://github.com/avasilkov/Wappalyzer/blob/master/src/drivers/npm/driver.js#L245). Looks like the URL are allowlisted prior any redirection :/

**Comment by revolunet** [comment]
https://github.com/AliasIO/wappalyzer/pull/5304

**Comment by revolunet** [comment]
this has been fixed upstream, waiting for a new release

**Comment by revolunet** [comment]
`noRedirect` option has been added to wappalyzer source, and reported in `wappalyzer-action`; looks better now : https://dashlord.incubateur.net/#/url/https%3A%2F%2Fmon-suivi-justice.beta.gouv.fr
